# Generated by Django 2.2.1 on 2019-05-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='myuser',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
